name: OSnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tensorflow=2.7.0
  - dask=2022.1.0
#  - dask-core
  - gsw=3.4.0
  - ipython=8.0.0
  - joblib=1.1.0
  - keras=2.6.0
#  - keras-gpu
  - matplotlib=3.5.1
  - numba=0.53.1
  - numpy=1.22.0
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - xarray=0.20.2
  - netcdf4=1.5.7
  - ipykernel=6.9.0
  - pip=21.3
  - pip:
    - cmocean